// Bundles the whole simple-admin source tree (src/) into exactly two distributable files:
//   dist/simple-admin.js   — src/index.js and everything it imports, minified ESM, one <script type="module">
//   dist/simple-admin.css  — src/theme/base.css + shadcn.css concatenated and minified, one <link>
//
// This script is dev-only tooling (esbuild is a devDependency, never imported by library source).
// The library itself has zero runtime dependencies and needs no build step to develop or use via
// individual ES modules — this bundle exists purely so a consuming app can reference two files
// instead of the whole source tree.

import { build } from 'esbuild';
import { mkdir, readFile, writeFile, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const srcDir = path.join(root, 'src');
const distDir = path.join(root, 'dist');

const banner = '/*! simple-admin — bundled build, generated by scripts/build.mjs. Do not edit. */\n';

async function buildJs() {
  const result = await build({
    entryPoints: [path.join(srcDir, 'index.js')],
    bundle: true,
    minify: true,
    format: 'esm',
    target: 'es2020',
    outfile: path.join(distDir, 'simple-admin.js'),
    banner: { js: banner },
    legalComments: 'none',
    metafile: true,
  });
  return result.metafile;
}

async function buildCss() {
  const files = ['theme/base.css', 'theme/shadcn.css'];
  const chunks = [];
  for (const rel of files) {
    const css = await readFile(path.join(srcDir, rel), 'utf8');
    chunks.push(`/* ---- src/${rel} ---- */\n${css}`);
  }
  const combinedPath = path.join(distDir, '_combined.css');
  await mkdir(distDir, { recursive: true });
  await writeFile(combinedPath, chunks.join('\n\n'), 'utf8');

  await build({
    entryPoints: [combinedPath],
    bundle: false,
    minify: true,
    outfile: path.join(distDir, 'simple-admin.css'),
    banner: { css: banner },
    legalComments: 'none',
  });

  const { unlink } = await import('node:fs/promises');
  await unlink(combinedPath);
}

async function report(label, filePath) {
  const { size } = await stat(filePath);
  console.log(`  ${label}: ${filePath.replace(root + path.sep, '')} (${(size / 1024).toFixed(1)} KB)`);
}

async function main() {
  await mkdir(distDir, { recursive: true });
  console.log('Building simple-admin...');
  await buildJs();
  await buildCss();
  console.log('Done:');
  await report('JS ', path.join(distDir, 'simple-admin.js'));
  await report('CSS', path.join(distDir, 'simple-admin.css'));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
